# Generated by Django 3.0.8 on 2020-07-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectuser',
            options={'verbose_name': 'Категоря объекта', 'verbose_name_plural': 'Категории объекта'},
        ),
    ]
