# Generated by Django 3.0.8 on 2020-07-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_user', '0005_auto_20200726_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectuser',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='object_user.Category'),
            preserve_default=False,
        ),
    ]
